### PR TITLE
fix(design-qa): Fix spacing issues within Content Intro & minor bugs seen within Microsite

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://jira.sdlc.merative.com/browse/MERATIVE-887

## Description

**Changed**

- This PR addresses multiple spacing issues seen when certain bands/patterns are stacked. See the ticket (https://jira.sdlc.merative.com/browse/MERATIVE-887) for more details.
- Also, this PR fixes minor FE display issues when the list item within the `Content Intro` block goes into two lines.

## Design Specs

- Figma Link -

## Test URLs for spacing issues
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/curam
- After (Changes from this PR): https://fix-space-qa-887--merative2--proeung.hlx.page/curam

## Test URLs for FE bugs seen in Microsite Missouri Landing
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/campaigns/curam/missouri
- After (Changes from this PR): https://fix-space-qa-887--merative2--proeung.hlx.page/campaigns/curam/missouri
  
## Testing Instruction

- Take a look at the issues outlined in this ticket (https://jira.sdlc.merative.com/browse/MERATIVE-887) and ensure that those things are addressed.

### CODE REVIEW

**Comment by keith-kaplan** [comment]
@proeung  this is looking great. A question for content entry on this page. 
https://fix-space-qa-887--merative2--proeung.hlx.page/curam (https://main--merative2--hlxsites.hlx.page/curam)

Should the content checkmarks section metadata still be there as it's own section? it looks like the spacing is working fine, but wanted to ensure the content entry didn't need to be one section. 
image

**Comment by proeung** [comment]
> Should the content checkmarks section metadata still be there as it's own section? it looks like the spacing is working fine, but wanted to ensure the content entry didn't need to be one section.

@keith-kaplan It should be in the same section. I forgot to move the stat into the same section as the Content Intro that has the checkmarks. Feel free to change this.

**Review by sachinmesh — CHANGES_REQUESTED** [review]
1. We can reduce this padding to 96px instead of 160px.
image


2. This component is breaking 
image

3. Stat component can also be updated as per recent PR.

**Comment by proeung** [comment]
@sachinmesh Which section are you referring to for "We can reduce this padding to 96px instead of 160px."? The screenshot that you've provided doesn't look correct.

> This component is breaking

This is an issue that's not scoped to this PR and will be handled in a separate ticket.

**Comment by sachinmesh** [comment]
This padding @proeung between the title and the first simple component.

image

**Comment by proeung** [comment]
@sachinmesh I just pushed a commit that should address your feedback about the spacing. Can you take a look again?

**Comment by sachinmesh** [comment]
This is good to go. Just one thing if we can update the title here to H1 instead of H2, as there is no H1 title on the page. @proeung @keith-kaplan 

image

**Review by sachinmesh — APPROVED** [review]

**Review by keith-kaplan — APPROVED** [review]
This looks good. Thank you.

**Pull request merged**
