### PR TITLE
feat(sidekick): upgrade block library to use new plugin

### LINKED ISSUE #239: Upgrade block library to use new plugin
Currently we have a block library that is feature rich. 

There is a new Sidekick library plugin project that has a lot more features that we should migrate to to make it easy for authors to create content 
Code: https://github.com/adobe/franklin-sidekick-library
Preview: https://main--rosalind-boilerplate--dylandepass.hlx.live/tools/sidekick/library.html?plugin=blocks

### PR DESCRIPTION
**Pull request by helms-charity**
Currently I've got a hard coded URL in the icons.js for testing purposes, I will change it before merging.
The test URL should not be any different than on MAIN after I moved createOptimizedPicture function.

## Issue

Fixes #239 

## Description

> This is a new redo of the sidekick block library and SVG icon copier.

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/blog
- After (Changes from this PR): https://239-sidekickupgrade--merative2--hlxsites.hlx.page/blog
  
## Testing Instruction
Currently I've got a hard coded URL in the icons.js for testing purposes, I will change it before merging.
Use URL 239-sidekickupgrade--merative2--hlxsites.hlx.page/tools/sidekick/library.html to view the new sidekick.

The /block-library documents were all updated to render properly with a description of the variation on the bottom of the preview area. 

To test blocks and sections, go to the HTML page and when you click on a block style, there's a button to copy it. You just have to paste this into a Word doc.

To test icons, choose "icons" from the top dropdown, then click on any SVG and it will copy the :icon-name: that you can paste into a document.

## authoring
There's a new line in the metadata to add when you would like to copy compound sections.
image

-

### CODE REVIEW

**Comment by proeung** [comment]
@helms-charity Is this PR ready for code and regression testing or are you still working on this feature?

**Comment by helms-charity** [comment]
It is ready for your QA and sign off, but you can't merge it until I put the $(host) variable back and whatever other linting it is complaining about.

**Review by proeung — COMMENTED** [review]
@helms-charity These changes look good overall! However, is there a way to add "Sections" to the list option (see attached)?

We want Content Authors to be able to sort through the listing and see all of the sections instead of having these sections be part of the `Blocks`.

Screenshot 2023-07-31 at 3 01 49 PM

**Comment by helms-charity** [comment]
@proeung no, the engineering team said the only created one option to copy page sections and they named it "blocks". When I asked about "what if I did blah blah blah" they told me that the core sidekick library code is still under development and that I should not go nuts with customization or I risk breaking it. They are rolling out the Templates option "very soon" I was told, maybe that will be a better place to put sections.

**Comment by helms-charity** [comment]
P.s. authors can use the search at the top if that helps?

**Review by proeung — APPROVED** [review]
@helms-charity Looks good from a code perspective!

Also, would it be feasible to apply styles to the info/helper area? Would be nice to add a max-width to the text container so that it's not taking up the whole window width (see attached).

Screenshot 2023-08-01 at 4 48 12 PM

-------

As to when these changes should be merged/make available for Content Authors, I'll defer to @keith-kaplan on this, since he's been working on the enablement/training doc for Franklin, which includes the usage of the library to copy blocks/tables.

**Comment by proeung** [comment]
@helms-charity @keith-kaplan I have some follow-up questions for this new library upgrade and figured that it's probably better to discuss them on a call. I'll send out an invite. In the meantime, let's keep this PR as "on-hold".

**Comment by helms-charity** [comment]
@proeung ok, I have time before 4pm today or just about all day tomorrow available.

**Comment by keith-kaplan** [comment]
I can join too if that time works.

**Comment by proeung** [comment]
@helms-charity Just wanted to follow up on this PR to see if some of the feedback mentioned in this comment has been addressed (https://github.com/hlxsites/merative2/pull/296#issuecomment-1665769482).

**Comment by helms-charity** [comment]
I had to shift to another priority but I will be able to get back to this tomorrow. In the meantime I am asking when the Templates feature will be available too.

**Pull request merged**
