### PR TITLE
Curam missouri microsite page fixes.

### PR DESCRIPTION
**Pull request by nimithshetty17**
## Issue

Fixes #[MERATIVE-905](https://merative.atlassian.net/browse/MERATIVE-905)

## Description

The latest designs for the Missouri campaign in microsite do not match the updated designs in Figma. It is mostly background color changes and addition of headline. The PR consists of fixes for that.

- Figma Link - https://www.figma.com/file/lcNLadWizxvzfhBpqds4hU/Curam---State-Microsite?type=design&mode=design

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/drafts/putra/campaigns/missouri
- After (Changes from this PR): https://curam-missouri-microsite-changes--merative2--nimithshetty17.hlx.page/drafts/putra/campaigns/missouri
  
## Testing Instruction

To test the changes as per the figma link provided above.

-

### CODE REVIEW

**Comment by nimithshetty17** [comment]
@anabarcelona @sachinmesh @keith-kaplan - These are the following issues addressed in the latest commit:-
1. Increase title to H1 ” Explore our platform” - Code side changes have been done, authoring side changes are pending.
2. Make sure space between H2 and first feature is 96px.
3. Remove bottom gray rule below the navigation bar- same update for mobile.
4. Reduce the space above full width image and below the list. It should be 96px.

**Comment by anabarcelona** [comment]
Hi @nimithshetty17, updated and added comments in the QA doc:
https://merative-my.sharepoint.com/:w:/p/abarcelona/EZLyhr7AsFBOuh-jptVHz4MBlMXA7ftxXnnF_viNr2WH8w?e=WaTod4

Happy to review together next time we meet. It's looking good!

**Comment by nimithshetty17** [comment]
@anabarcelona @keith-kaplan @sachinmesh - Please find the fixes for the new commit below:-
1.	Reduce the space above full width image and below the list. It should be 96px -Done
2.	When you scroll down to the case studies, can the nav slide over to show Case studies is highlighted? -Done
3.	“Why Curam” shouldn’t be selected when you are in the platform area of the page. -Done.
4.  Currently it’s not aligning to our gutters -Done
5.  Remove bottom gray border fro mobile and tablet. Please add that back for Desktop only -Done
6.  we still need to increase the size of Explore our platform title to 64px -Done

**Comment by anabarcelona** [comment]
Thank @nimithshetty17, I've reviewed and marked things as done! Some are still some remaining things on the list. Thank you :)

**Comment by anabarcelona** [comment]
Thanks Nimith once again! We are so close... there are 3 open tasks still remaining in the doc...

**Comment by nimithshetty17** [comment]
@anabarcelona @sachinmesh - These are the pending changes and the fixes are added in the latest commit:-
1. Adjust the gradient for 25+
2. The only title that needs to be our H1 size is the “Explore the platform” title, please adjust.
3. The arrow buttons fill needs to be in bone. Currently they are filled with white. Please update.
Rest which are not marked as Done is:-
1.	Remove bottom gray rule below the navigation bar- same update for  mobile please. The line needs to be there on 
        desktop. It’s no longer there. Please add that back for Desktop only. See screenshot below- bottom rule divider is 
         missing on desktop. (Discussed with Sachin he said it is reflecting)
2.	Update the artwork to match the design. (Authoring change)
3.	Please make the phone number a link... on mobile it should call the number. (Authoring change)

**Comment by anabarcelona** [comment]
@nimithshetty17 question on #5 above... who exports the artwork? And where is it saved for the content authors to upload it?

**Comment by anabarcelona** [comment]
All the other updates you mentioned above look good! Thanks @nimithshetty17

**Comment by nimithshetty17** [comment]
> @nimithshetty17 question on #5 above... who exports the artwork? And where is it saved for the content authors to upload it?

@anabarcelona - We usually get it from Sachin and then the content author will drop the image in the word document.

**Comment by anabarcelona** [comment]
@nimithshetty17, okay, sounds like I need to export them and save them. Where are they usually saved? Thank you!

**Comment by nimithshetty17** [comment]
> @nimithshetty17, okay, sounds like I need to export them and save them. Where are they usually saved? Thank you!

@anabarcelona - We don't save the images anywhere in Franklin. You can upload it in the Jira ticket or mail it, we'll replace the image.

**Review by keith-kaplan — APPROVED** [review]
Confirmed with Ana and Nimith that is good to get merged.

**Pull request merged**
