### PR TITLE
Stat with illustration padding issue

### PR DESCRIPTION
**Pull request by nimithshetty17**
Fixes [MERATIVE-950](https://merative.atlassian.net/browse/MERATIVE-950)

## Description

The stat with illustration block was designed to only have an image below it. We would like to update this block to ensure there is the proper padding added above/below when an image is not present.

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/drafts/Keith/real-world-evidence-copy
- After (Changes from this PR): https://stat-with-illustration-padding-issue--merative2--nimithshetty17.hlx.page/drafts/Keith/real-world-evidence-copy

### CODE REVIEW

**Comment by nimithshetty17** [comment]
@keith-kaplan have added the bottom padding. Let me know if this is ok.

**Review by keith-kaplan — CHANGES_REQUESTED** [review]
@nimithshetty17  can we also add a class or add an edit that will make remove the top padding. I think it's default at 160px.

**Comment by keith-kaplan** [comment]
No worries. This looks good to me. @sachinmesh  @anabarcelona  want to take a look? https://stat-with-illustration-padding-issue--merative2--nimithshetty17.hlx.page/drafts/Keith/real-world-evidence-copy

**Comment by keith-kaplan** [comment]
@nimithshetty17  I just saw the Figma file. I think we need to make the number stat a gradient like the content intro stat block.

**Comment by sachinmesh** [comment]
The width of the stat component is wrong, it should be desktop is 360px, tablet 275px, mobile 270px @nimithshetty17 

image


CC: @keith-kaplan @anabarcelona

**Comment by nimithshetty17** [comment]
@sachinmesh please check now.
cc: @keith-kaplan

**Review by sachinmesh — APPROVED** [review]
Checked this URL 
https://stat-with-illustration-padding-issue--merative2--nimithshetty17.hlx.page/drafts/Keith/real-world-evidence-copy

Looks good to me.

@nimithshetty17 @keith-kaplan

**Review by keith-kaplan — APPROVED** [review]
Looks good.

**Pull request merged**
