### PR TITLE
feat(content): add Content block and cleanup

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://jira.sdlc.merative.com/browse/MERATIVE-778

## Description

**New**

- This PR adds a new block called "Content" `/blocks/content` as well as cleaning up styles and temporarily hiding the meta wrapper block that's designed for the new upgrade version of the block library.
- Variations
  - Content - Simple
  - Content - Checklist
  - Content - Complex

## Design Specs

- Figma Link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1634%3A13852&mode=design&t=v6xSx8pIiPAF0sDO-1

## Test URLs

- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/block-library/blocks/content
- After (Changes from this PR): https://feat-content-block--merative2--proeung.hlx.page/block-library/blocks/content

Screenshot 2023-08-07 at 4 09 08 PM

## Testing Instruction

- Visit the preview page of the "Content" Block - https://feat-content-block--merative2--proeung.hlx.page/block-library/blocks/content
- Ensure that the following variations match with the design (see Figma link)
  - Content - Simple
  - Content - Checklist
  - Content - Complex

### CODE REVIEW

**Review by sachinmesh — CHANGES_REQUESTED** [review]
Some observations

1. Right side text block should be center aligned to the left quarter circle block in all cases.
2. Dimensions of quarter circle block should be 552 X 455
     
image

image



3. Spacing between circle checkmark with thr right text should be 10px and not 16px. 

image


4. Font style of paragraph subheading should be H5 - 16px Alliance no.1 Regular 

image


5. All the components, Left and right blocks should be center aligned.

image
 

@proeung @nimithshetty17 @keith-kaplan

**Comment by proeung** [comment]
@sachinmesh I just pushed up a [commit](https://github.com/hlxsites/merative2/pull/311/commits/7a4823e9bd01998bfadc69e771ee6a5ab4a93873) that addresses all of your feedback. Can you take a look again?

**Comment by sachinmesh** [comment]
All the feedbacks are fixed, only in mobile the spacing between learn more CTA and the content above it should be 32 px and  not 48px. 


image

@proeung

**Review by sachinmesh — APPROVED** [review]
All issues are fixed.

@proeung @keith-kaplan

**Pull request merged**
