### PR TITLE
feat(masthead): Updated Mega-menu to support "Support page" links

### PR DESCRIPTION
**Pull request by sahmad-merative**
The purpose of updating the Masthead/Nav Megamenu is to streamline the display of the Support links so that they're easily accessible within the menu.

This PR is only for Frankiln implementation.

## Issue [MERATIVE-872](https://jira.sdlc.merative.com/browse/MERATIVE-872)

Fixes #

## Description

The purpose of updating the Masthead/Nav Megamenu is to streamline the display of the Support links so that they're easily accessible within the menu.

This PR is only for Frankiln implementation.

**New**

Updated Mega-menu to support "Support page" links

## Design Specs

> If applicable, add the direct link to the design specs of the component/feature that's part of this PR.

- Figma Link - https://www.figma.com/file/yz6IpI3HjO29yKGxxhg4vk/Curam-mega-menu-additions?type=design&node-id=412%3A9415&mode=design&t=9Iy8uVr1yXcE2AvM-1

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/
- After (Changes from this PR): https://872-masthead--merative2--sahmad-merative.hlx.page/
  
## Testing Instruction

> If applicable, please describe the tests that you ran to verify your changes. Provide instructions and link to the `hlx` deploy preview so that QA and the design team can provide proper testing.

-

### CODE REVIEW

**Comment by sachinmesh** [comment]
Everything looks good, fonts, icons at all brakpoints. only the alignment here is wrong @proeung 

image

**Review by proeung — CHANGES_REQUESTED** [review]
@sahmad-merative Code looks good overall. You just need to resolve some of the lint check issues as well as the alignment/spacing bugs that @sachinmesh mentioned above.

**Review by sachinmesh — APPROVED** [review]
Checked at all breakpoints. All font styles are correct as per design. Good to go.

**Comment by proeung** [comment]
@sahmad-merative I'm still seeing the linting errors (https://github.com/hlxsites/merative2/actions/runs/6258201007/job/16991775327?pr=338). Can you take a look?

**Review by proeung — APPROVED** [review]
@sahmad-merative LGTM! Once, the data source has been changed back to the default fragments path, I'll go ahead and merge this PR down.

**Comment by sahmad-merative** [comment]
> @sahmad-merative LGTM! Once, the data source has been changed back to the default fragments path, I'll go ahead and merge this PR down.

I am waiting for @sharathmrft to complete testing and approve. Once that is done I'll revert back to default fragment path.

**Review by sharathmrft — APPROVED** [review]
@sahmad-merative 
It LGTM
@sachinmesh

**Comment by sahmad-merative** [comment]
@proeung The data source has been changed back to the default fragments path, and all the lint issues are also resolved.
This PR is ready to be merged.

**Pull request merged**
