### PR TITLE
feat(back-to-top): remove back to top in favor of Drift

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://jira.sdlc.merative.com/browse/MERATIVE-815

## Description

**Removed**

- This PR removes the `Back to Top` button functionality so that we can use the bottom right hand corner for the Drift Chatbot Widget.

## Design Specs

- Figma Link - N/A

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/
- After (Changes from this PR): https://feat-drift-remove-back-to-top--merative2--proeung.hlx.page/
  
## Testing Instruction
- Visit this deploy preview (https://feat-drift-remove-back-to-top--merative2--proeung.hlx.page).
- Ensure that the "Back to Top" button is no longer visible.
- Ensure that the Drift button is visible once, the playbooks configs have been implemented to the test URL above.
- https://feat-drift-remove-back-to-top--merative2--proeung.hlx.page/#bot_test-5086233-t9fx4CHq

### CODE REVIEW

**Comment by proeung** [comment]
@keith-kaplan Looks good! I'm going to review this on our Merative.com design call tomorrow and see if folks have any feedback on this. In the meantime, I'll leave this PR open.

Screenshot 2023-08-07 at 1 58 42 PM
Screenshot 2023-08-07 at 1 58 48 PM

**Comment by aavilamer** [comment]
@proeung Let's update the use of the logo in the center. We should just use the default chat icon like pure storage. 
MicrosoftTeams-image (78)

**Comment by proeung** [comment]
> @proeung Let's update the use of the logo in the center. We should just use the default chat icon like pure storage.

@aavilamer Yep, we can upload a new custom icon for this avatar. I looked through our Icon library within our design system (see [link](https://www.figma.com/file/TyajZb165gYM43ULg8nQv5/Core-%E2%80%93-Merative-Digital-Design-System?type=design&node-id=14%3A1213&mode=design&t=1NpAFR6H0TLI3cXI-1)), didn't find a chat bubbles icon that works.

Is there a style or SVG that you have in mind? Here are some options that we can look at.
- https://thenounproject.com/icon/chat-bubbles-1113606/
- https://thenounproject.com/icon/chat-bubbles-396407/
- https://thenounproject.com/icon/chat-bubbles-975775/

**Comment by aavilamer** [comment]
Okay thanks – we use phosphor icons for our icons. I added this one in light to the design system - https://www.figma.com/file/TyajZb165gYM43ULg8nQv5/Core-%E2%80%93-Merative-Digital-Design-System?type=design&node-id=1%3A10&mode=design&t=4On2dXKvrNU8DY8J-1

the site: https://phosphoricons.com/, We use light value of the icon you can select in the phosphor icon plugin in figma FYI
[A screenshot of a chat  Description automatically generated]

From: Putra Bonaccorsi ***@***.***>
Date: Tuesday, August 8, 2023 at 4:16 PM
To: hlxsites/merative2 ***@***.***>
Cc: ANNMARIE AVILA ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [hlxsites/merative2] feat(back-to-top): remove back to top in favor of Drift (PR #310)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
ALERT: This Message Came From External Sender, Please Avoid Clicking Any Links or Opening Attachments If The Sender Is Unknown.


@proeung<https://github.com/proeung> Let's update the use of the logo in the center. We should just use the default chat icon like pure storage.

@aavilamer<https://github.com/aavilamer> Yep, we can upload a new custom icon for this avatar. I looked through our Icon library within our design system (see link<https://www.figma.com/file/TyajZb165gYM43ULg8nQv5/Core-%E2%80%93-Merative-Digital-Design-System?type=design&node-id=14%3A1213&mode=design&t=1NpAFR6H0TLI3cXI-1>), didn't find a chat bubbles icon that works.

Is there a style or SVG that you have in mind? Here are some options that we can look at.

  *   https://thenounproject.com/icon/chat-bubbles-1113606/
  *   https://thenounproject.com/icon/chat-bubbles-396407/
  *   https://thenounproject.com/icon/chat-bubbles-975775/

**Comment by proeung** [comment]
@aavilamer Here's the latest preview using the icon that we discussed. https://feat-drift-remove-back-to-top--merative2--proeung.hlx.page/#bot_test-5086233-t9fx4CHq

Screenshot 2023-08-09 at 1 28 47 PM
Screenshot 2023-08-09 at 1 28 52 PM

**Comment by aavilamer** [comment]
@keith-kaplan where did the name land? Bot could be MerativeChat, MerativeConnect, MeraTalk, Product Advisor...throwing a few themes out there.

**Comment by proeung** [comment]
> @keith-kaplan where did the name land? Bot could be MerativeChat, MerativeConnect, MeraTalk, Product Advisor...throwing a few themes out there.

@aavilamer Personally, I like `MerativeChat`, but defer to you and @keith-kaplan on what to name the bot.

Also, @keith-kaplan do we have a date on when we'll be switching on Drift for the merative.com domain name? I think can merge this PR to remove the "Back to Top" button if we're ready to roll this out unless we want to wait until this button is removed on AEM (see - https://jira.sdlc.merative.com/browse/MERATIVE-814) as well.

**Comment by keith-kaplan** [comment]
Still confirming the name, but we're thinking Merative Bot. For the merge. This is not going live until 2nd week of Sept so I think we can do this in a few weeks.

**Review by keith-kaplan — APPROVED** [review]
looks good

**Pull request merged**
