### PR TITLE
feat(microsite): Add Solution Header and Solution Footer blocks used within custom campaign/microsites 

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes https://merative.atlassian.net/browse/MERATIVE-878 & https://merative.atlassian.net/browse/MERATIVE-879

## Description

**New**

- Solution Header `/blocks/solution-header` - This block manages and displays the anchor/table of contents navigation used on a single campaign/microsite.
- Solution Footer `/blocks/solution-footer` - This block manages and displays fragment/related content (See - `website > fragments > footer > footer-small`) (see [link](https://merative.sharepoint.com/:w:/s/Merative.comWebsite/ESfsn8gNRoZJjz2Zx-lV5X4B-TVE1F9z8_rfjCSlCCDrIA?e=jOr4jt)) for the custom footer.

**Changed**

- Fixes grid container of the CTA block

## Design Specs

- Figma Link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=496%3A6561&mode=dev

## Test URLs
 
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/drafts/putra/campaigns/missouri
- After (Changes from this PR): https://feat-solution-header--merative2--proeung.hlx.page/drafts/putra/campaigns/missouri
  
## Testing Instruction

Screenshot 2023-09-29 at 11 44 38 AM
Screenshot 2023-09-29 at 11 44 55 AM
Screenshot 2023-09-29 at 11 44 44 AM

- Visit the "After" deploy preview and ensure that the behaviors and styles of the Header/Nav and Footer align with the design specs.

### CODE REVIEW

**Review by sachinmesh — CHANGES_REQUESTED** [review]
1. Dark grey stroke can seen in the header above the highlighter

  
image

image

2. In mobile, the seperator line should be 32px height only. 

image

3. on horizontal scroll, gradient is missing

image

4. Logo should be of 38px height with compared to width, for curam it is, 130X38px

**Comment by proeung** [comment]
@sachinmesh I just pushed up a commit to address some of the spacing and logo size issues that you mentioned above. 

As for the height of the borderline on the sticky nav scroll and the gradient on the scroll, let's discuss that on our next design call. I have some concerns about the feasibility given the current timeline and dev resources.

cc: @aavilamer 

https://javascript.plainenglish.io/how-to-create-horizontal-vertical-scroll-shadows-26aa7a7f00a0

**Review by keith-kaplan — APPROVED** [review]
@proeung  just took a look and this looks solid.

**Comment by proeung** [comment]
@keith-kaplan Great! Just need @sachinmesh to re-review/approve and this PR is ready for merge unless there are additional changes.

**Review by sachinmesh — APPROVED** [review]

**Pull request merged**
