### PR TITLE
fix(product-landing): Fix various blocks and section used within MDX landing page

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://jira.sdlc.merative.com/browse/MERATIVE-822

## Description
- This PR fixes various blocks and sections used within the MDX landing page (`/clinical-decision-support`) version within Franklin.

**New**

-  Stat with Illustration - https://fix-822-product-landing-issues--merative2--proeung.hlx.page/block-library/blocks/stat-with-illustration

Screenshot 2023-08-31 at 12 23 52 PM

**Changed**

- The following are blocks that have been changed:
  - Linkable Cards - https://fix-822-product-landing-issues--merative2--proeung.hlx.page/block-library/blocks/linkable-cards
  - Content Intro - https://fix-822-product-landing-issues--merative2--proeung.hlx.page/block-library/blocks/content-intro
  - Accordion - https://fix-822-product-landing-issues--merative2--proeung.hlx.page/block-library/blocks/accordion

Screenshot 2023-08-31 at 12 23 43 PM
Screenshot 2023-08-31 at 12 23 59 PM
Screenshot 2023-08-31 at 12 24 08 PM

**Removed**

- Removed the `Content Band Checkmark` block and merged it to the `Content Intro` block instead. This change helps consolidate code (CSS and JS), removes duplications, and creates consistency. FYI. @nimithshetty17 
  - remove `content-band-checkmarks/content-band-checkmarks.js`
  - remove `content-band-checkmarks/content-band-checkmarks.css`

## Design Specs

- Figma Link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1459%3A18597&mode=design&t=b59iXh6I3cYTbZkE-1

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/clinical-decision-support
- After (Changes from this PR): https://fix-822-product-landing-issues--merative2--proeung.hlx.page/clinical-decision-support
  
## Testing Instruction

- Visit the version of the MDX landing in Franklin (https://fix-822-product-landing-issues--merative2--proeung.hlx.page/clinical-decision-support)
- Ensure that the patterns within this page match the designs.

### CODE REVIEW

**Comment by proeung** [comment]
@sachinmesh Can I get design QA for this PR?

**Comment by keith-kaplan** [comment]
@proeung  a few comments.

- On CDS page for accordion, the title should be H2 vs H3. I changed here - https://fix-822-product-landing-issues--merative2--proeung.hlx.page/clinical-decision-support (Get to know our capabilities)
- Video resources card needs to open in light box vs linking off to youtube. Can this be solved in the other Jira issue being worked on?
- Can we confirm the difference in section divider with these items? Divider vs Divider (layout). It looks like they are both using inline code, but it seems one divider is gradient. I see both use the no-pad class in the metadata table.

Accordion example - https://fix-822-product-landing-issues--merative2--proeung.hlx.page/events/2023-zelta-user-conference. It looks like this block is not affected by lacking the new theme metadata attribute.

**Review by sharathmrft — DISMISSED** [review]
@proeung 
Link is not properly aligned screenshot is attached below
image
@sachinmesh

**Comment by sharathmrft** [comment]
@proeung Video resources card modal popup goes off as shown below.
image

**Review by sachinmesh — DISMISSED** [review]
In Accordion
1. Padding between heading and description should be 32px and not 48px.

image

2. Padding between the description and the questions should be 48px.
3. Font style for description should be 21px. see the figma link for revamped MDX design https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=2693-15913&mode=design&t=88QCgXZUgqm4tMpJ-4

4.  In Open state,  the padding between the title question and description below it should be 32px. 
image


All points same for table and mobile  

5. In content band checkmark, the checkmark text font style should be 21px regular and not medium.

    
image

6. In resources component, The title width should be 744px wide and not 648.
    
    
image



@proeung @keith-kaplan @sharathmrft @sahmad-merative @nimithshetty17

**Comment by proeung** [comment]
@sharathmrft @sachinmesh I just pushed up a commit that should address majority of your feedback.

> Link is not properly aligned screenshot is attached below

Fixed

> Video resources card modal popup goes off as shown below.

This feature will be addressed in this ticket (https://jira.sdlc.merative.com/browse/MERATIVE-858). A separate PR will be opened up for this.

> Padding between heading and description should be 32px and not 48px.

Fixed

> Padding between the description and the questions should be 48px.

Fixed

> Font style for description should be 21px. see the figma link for revamped MDX design https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=2693-15913&mode=design&t=88QCgXZUgqm4tMpJ-4

@sachinmesh This spec doesn't align with the Accordion pattern design specs that are in our design system, which has the description at `16px` (see - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=1459%3A19121&mode=design&t=003mQGakUdFWhOL9-1). Can you touch base with Ana to verify which specs is correct?

**Review by keith-kaplan — APPROVED** [review]
Looks good.

**Comment by proeung** [comment]
@keith-kaplan Thanks for the review/approval! Merging PR so that we can move forward with the campaign landing page (https://fix-822-product-landing-issues--merative2--proeung.hlx.page/campaigns/curam/missouri) and this overall design QA ticket (https://jira.sdlc.merative.com/browse/MERATIVE-880).

**Pull request merged**
