### PR TITLE
feat(references): Add a new block called References

### PR DESCRIPTION
**Pull request by nimithshetty17**
Fixes #[MERATIVE-825](https://merative.atlassian.net/browse/MERATIVE-825)

## Description

Create a new block called "References" - /blocks/references with the correct CSS styling that allows for these links to show up properly.

**New**

image

**Changed**

image

## Design Specs

> If applicable, add the direct link to the design specs of the component/feature that's part of this PR.

- Figma Link - https://www.figma.com/file/vw24IPXXt4vCh9BNumka9A/Web--Merative-Digital-Design-System-2.0?type=design&node-id=10089-44822&mode=design&t=qStX3jR9aAwB4mEL-4

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--nimithshetty17.hlx.page/drafts/nimith/references-block
- After (Changes from this PR): https://references-section-block--merative2--nimithshetty17.hlx.page/drafts/nimith/references-block
  
## Testing Instruction

>To verify the references section block as per design.

-

### CODE REVIEW

**Review by sachinmesh — CHANGES_REQUESTED** [review]
Font style all looks good at all breakpoints. Only the Font color should be Neutral 140 which is 5C5A57

@proeung @nimithshetty17 @keith-kaplan 

image

**Review by sachinmesh — APPROVED** [review]
Good to merge. @nimithshetty17 @keith-kaplan @proeung

**Comment by keith-kaplan** [comment]
@nimithshetty17  i'm going to put this on a real blog in the draft folder to test it one more time.

**Comment by keith-kaplan** [comment]
@sachinmesh  can you take a look at this one I updated - https://references-section-block--merative2--nimithshetty17.hlx.page/blog/oncology-research-deserves-cutting-edge-solutions

Want to make sure we have an example of this in a real blog post.

**Review by proeung — CHANGES_REQUESTED** [review]
@nimithshetty17 Looks good, but let's add an empty `/blocks/references/references.js` file (eg. https://github.com/hlxsites/merative2/blob/main/blocks/article-quote/article-quote.js) since Franklin expects this in the block creation script (see - https://github.com/hlxsites/merative2/blob/main/scripts/lib-franklin.js#L391) and we can cut on the 404 error.

Screenshot 2023-10-10 at 9 51 55 AM

**Comment by sachinmesh** [comment]
> @sachinmesh can you take a look at this one I updated - https://references-section-block--merative2--nimithshetty17.hlx.page/blog/oncology-research-deserves-cutting-edge-solutions
> 
> Want to make sure we have an example of this in a real blog post.

1. Sources text style should be H3 - 32px Source serif pro light 
image

2. Spacing between Heading and body text should be 48px.

Rest is good to go. @keith-kaplan

**Review by proeung — APPROVED** [review]
LGTM!

**Comment by keith-kaplan** [comment]
Going to merge.

**Pull request merged**
