### PR TITLE
Added Drift popup code

### PR DESCRIPTION
**Pull request by chandans1316**
## Issue

Fixes: https://merative.atlassian.net/browse/MERATIVE-885

## Description
https://merative.atlassian.net/browse/MERATIVE-885
> The existing marketo form block on merative.com/contact needs to be updated with a javascript listener called "fastlane".

## Test URLs
Fix: https://merative.atlassian.net/browse/MERATIVE-885
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/contact
- After (Changes from this PR): https://issue-885-drift-script--merative2--hlxsites.hlx.page/contact

### CODE REVIEW

**Review by joehanchoi — APPROVED** [review]

**Comment by joehanchoi** [comment]
Form will pause redirect once Playbook chatbot appears now

**Comment by keith-kaplan** [comment]
@joehanchoi  testing now.

**Review by keith-kaplan — COMMENTED** [review]
Confirmed that this is working. I've used the existing conditions for the fastlane playbook and I can get it fire. We will plan to merge to Main tomorrow when we're on a Drift call. We'll also update the conditions to not using the testing emails.
image

**Review by keith-kaplan — APPROVED** [review]
Just tested with the updated targeting in Drift. Confirmed it works.

**Pull request merged**
