### PR TITLE
feat(leadspace): add leadspace brand logo style

### PR DESCRIPTION
**Pull request by nimithshetty17**
## Issue

Fixes #[MERATIVE-776](https://jira.sdlc.merative.com/browse/MERATIVE-776)

## Description

We have a "Leadspace" block created in Franklin, however, we need to add a variation where the brand logo can be inserted into the block table within the Sharepoint docs.

**New**

image

## Design Specs

> If applicable, add the direct link to the design specs of the component/feature that's part of this PR.

- Figma Link - https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=202-40370&mode=design&t=k3Wzg0Qy7d9YQrGa-0

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--nimithshetty17.hlx.page/block-library/blocks/leadspace
- After (Changes from this PR): https://leadspace-brand-logo--merative2--nimithshetty17.hlx.page/block-library/blocks/leadspace
  
## Testing Instruction

To test the leadspace with brand logo and its responsiveness with respect to the design across all devices.

### CODE REVIEW

**Review by sachinmesh — CHANGES_REQUESTED** [review]
Checked only the product logo leadspace. Let me know, if other leadspace are also needs to be checked.

1. On desktop, the height should be 55px for product logos 
image
mobile and tablet the height should be 45px for the product logos 
image

@nimithshetty17 @proeung @keith-kaplan

**Comment by nimithshetty17** [comment]
@sachinmesh - Please have a look now.

**Review by sharathmrft — CHANGES_REQUESTED** [review]
@nimithshetty17 
1.Video player is not playing the video
image

2. There is variations in the Buttons size
image

**Comment by sachinmesh** [comment]
HI @nimithshetty17 
The primary CTA missing the arrow style.  Rest is good to go.
image

**Comment by nimithshetty17** [comment]
@sachinmesh - Arrow is added as well.

**Review by sachinmesh — APPROVED** [review]
This is good to go now, as the arrow is also added in the primary CTA of the product specific leadspace. 
image

@proeung @nimithshetty17 @keith-kaplan @sharathmrft

**Comment by nimithshetty17** [comment]
@proeung - Updated all the changes requested. Please let me know if there are any concerns.

**Review by proeung — CHANGES_REQUESTED** [review]
@nimithshetty17 Your latest changes looks good, but I noticed that you were using a new arrow icon (`arrow-right.svg`) in the button. Just wanted to note that we already have an arrow icon SVG within the `/icons` directory within this repo (https://github.com/hlxsites/merative2/blob/main/icons/arrow.svg?short_path=f27ac62) and there's no need to upload a separate version.

Sharepoint format for primary button: `Speak to sales:arrow:`

**Things to change/clean up:**
- Remove this duplicate arrow SVG that you've uploaded (see [link](https://merative.sharepoint.com/:u:/s/Merative.comWebsite/ESuWLBvay1JMuMGbggb2QykBtLD5ie0Pf_LmlNXCFwPhmw?e=5XdC4o) ).
- Push up a commit to adjust the existing `arrow.svg` code to use the following SVG code with the proper viewBox value of 24x24px for consistent scaling.

Screenshot 2023-08-04 at 11 59 45 AM

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3.75 12.6152H20.25" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M13.5 5.86523L20.25 12.6152L13.5 19.3652" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

Once, these changes are in, we can mark this PR as `ready for merge`.

cc: @keith-kaplan

**Comment by nimithshetty17** [comment]
@proeung - I have committed the changes for the arrow icon.  Please let me know if there are any concerns.

**Review by proeung — APPROVED** [review]
@nimithshetty17 LGTM!

This PR is blocked from being merged until @sharathmrft has reviewed and approved it.

**Comment by sharathmrft** [comment]
@nimithshetty17 @proeung 
A small observation underline is thick in tab and mobile for Inline/Tertiary link as shown below rest is good to go.

image

@Shalini-SB @keith-kaplan

**Comment by proeung** [comment]
@sharathmrft Thanks for the review. Yeah, I noticed the odd line height issue for the tertiary link on the mobile breakpoint as well. @nimithshetty17 Can you fix this?

**Review by proeung — CHANGES_REQUESTED** [review]
@sharathmrft Thanks for the review. Yeah, I noticed the odd line height issue for the tertiary link on the mobile breakpoint as well. @nimithshetty17 Can you fix this?

**Comment by nimithshetty17** [comment]
@sharathmrft - Please review this now.

**Review by proeung — APPROVED** [review]
@nimithshetty17 Looks like you've added different line height values to the tertiary link for mobile (line-height-160) and desktop (line-height-120), which is incorrect.

I went a head and push up a commit (https://github.com/hlxsites/merative2/pull/309/commits/20d2f12ca4787249d9deb2cf2e997229909bd30c) to fix and clean up the format of the code. Tertiary link line height is looking inconsistent on all breakpoints now. I'm going to mark and merge this PR down.

Screenshot 2023-08-10 at 9 38 43 AM
Screenshot 2023-08-10 at 9 38 52 AM

**Pull request merged**
