### PR TITLE
fix(thought-leadership): adjust the function that checks if a card has a specific attribute value

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://jira.sdlc.merative.com/browse/MERATIVE-812 

## Description
**Changed**

- This PR fixes and clean up the function that checks if a card has a specific attribute value and sets `active-card` or `hidden`.
- These changes are solving an issue where there are some articles/pages are not showing up in "Thought leadership" when in the `Health Insights` page and the `success stories` filtered are checked. 

## Design Specs

- Figma Link - https://www.figma.com/file/dFJwrp6VkUMSirF2KMLRMx/Thought-leadership-library?type=design&node-id=787-25468&mode=design&t=pRNHGuEjJwkvu9Sy-0

## Test URLs

Screenshot 2023-08-01 at 4 11 08 PM

- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/thought-leadership/health-insights?content-types=Success+stories
Screenshot 2023-08-01 at 4 10 40 PM

- After (Changes from this PR): https://fix-tl-content-type-filter--merative2--proeung.hlx.page/thought-leadership/health-insights?content-types=Success+stories
  
## Testing Instruction

- Visit this page (https://fix-tl-content-type-filter--merative2--proeung.hlx.page/thought-leadership/health-insights?content-types=Success+stories)
- Ensure that the following success stories are showing up correctly.
  - https://main--merative2--hlxsites.hlx.page/documents/case-study/ballad-health-advanced-predictive-modeling
  - https://main--merative2--hlxsites.hlx.page/documents/case-study/health-insights-identify-savings-speciality-conditions
- Also, check the Blog - https://fix-tl-content-type-filter--merative2--proeung.hlx.page/blog to ensure that the filtering still functions correctly there as well.

### CODE REVIEW

**Review by helms-charity — APPROVED** [review]
Looks good

**Comment by sharathmrft** [comment]
@proeung Can we have updated Query Index SharePoint to verify the display cards according to filters selection

@keith-kaplan  @Shalini-SB

**Comment by proeung** [comment]
@sharathmrft Here's the query index (see [link](https://main--merative2--hlxsites.hlx.page/query-index.json)).

**Review by keith-kaplan — APPROVED** [review]
Looks great. Thank you.

**Pull request merged**
