### PR TITLE
feat(tag-picker): Enable search + copy tags interface for Content Authors

### LINKED ISSUE #191: Create a tagging taxonomy hierarchy like the Adobe Blog
We want to create a "pick your tag" spreadsheet like the Adobe blog for content authors. We have noticed inconsistencies in the topics/tags being used on blogs and some other pages. We'd like to use a solution like this or something similar to make keep tagging consistent.

https://main--blog--adobe.hlx.page/tools/tagger/index.html

image

### PR DESCRIPTION
**Pull request by helms-charity**
## Issue

Fix #191 

## Test URLs
  
- Before: https://main--merative2--hlxsites.hlx.page/
- After: https://191-tagpicker--merative2--hlxsites.hlx.page/tools/tagger/index.html
  
## How to test

Besides being it's own page (instructions are on it), a link was added to the sidekick for the tagger.
To test, temporarily edit the sidekick's Github URL to end in /tree/191-tagpicker. 
Navigate to a Sharepoint page, and you should see a new button called "tagger" which opens the tagging tool in a new browser tab.
image

### CODE REVIEW

**Comment by proeung** [comment]
@helms-charity Any progress on this draft PR? How close are we to enabling a tagging taxonomy hierarchy feature that provides consistent tag values within our docs?

**Review by keith-kaplan — COMMENTED** [review]
@helms-charity  this is looking good. I'm drafting up some copy we can put in the HTML at the top for descriptions of each tag.

**Review by proeung — APPROVED** [review]
Looks good from a code perspective.

Feel free to merge this down once you receive the copy from @keith-kaplan for the description/intro area.

Also, @keith-kaplan, just a suggestion, it might be good to include the link to the spreadsheet where these terms are being managed so that Caroline and trusted authors can reference it and make changes, unless, we just want to keep the editing process to one owner.

**Review by keith-kaplan — CHANGES_REQUESTED** [review]
@helms-charity  may we please add the following as a list under the text at the top.

•	**Categories** = will place your blog article in the correct category area per the main blog navigation
•	**Audience** = the audience group the content is created for
•	**Asset type** = the type of asset on the page. Primarily used for PDFs and offer registration pages
•	**Page type** = the type of webpage. It must be used on all web pages.
•	**orgFunction** = the owning organization function of the webpage. It must be used on all web pages.
•	**Topics** = will place your blog article in the correct topic area per the main blog navigation
•	**Parent** = required for analytics. It must be used on all web pages. 
•	**Product Family** = required for analytics. It must be used on all web pages.

**Comment by helms-charity** [comment]
@keith-kaplan added, have a look now.

**Review by keith-kaplan — APPROVED** [review]
This looks good on my side.

**Pull request merged**
