### PR TITLE
Issue 956 email icon hyperlinks

### PR DESCRIPTION
**Pull request by chandans1316**
## Issue

Fixes: https://merative.atlassian.net/browse/MERATIVE-956

## Description

> On the "Headshot" block, when an email hyperlink is used in content, it shows up as a link icon.

## Test URLs

- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/drafts/Keith/common-spirit-health
- After (Changes from this PR): https://issue-956-email-icon-hyperlinks--merative2--hlxsites.hlx.page/drafts/Keith/common-spirit-health

### CODE REVIEW

**Review by joehanchoi — CHANGES_REQUESTED** [review]
Icon is oversized on Safari browser windows

**Review by joehanchoi — APPROVED** [review]
Resolved Safari issue

**Review by keith-kaplan — CHANGES_REQUESTED** [review]
The email icon is looking good. There needs to be a change to the border top line to ensure spans the fill width of the div. Right now it does not happen. 

Design System
image


Webpage
image

**Review by keith-kaplan — APPROVED** [review]
Changes look good and confirmed works on mobile.

**Pull request merged**
