### PR TITLE
Add multiple suppor

### PR DESCRIPTION
**Pull request by VladimirZaets**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix https://github.com/hlxsites/merative/issues/109

Test URLs:

- Before: https://main--merative2--hlxsites.hlx.page/drafts/vzaets/4-ways-rsna-laid-out-imaging-ai-future
- After: https://author-bio-multiple--merative2--hlxsites.hlx.page/drafts/vzaets/4-ways-rsna-laid-out-imaging-ai-future

### CODE REVIEW

**Comment by VladimirZaets** [comment]
@amol-anand I implemented function part (still need to update blog-home) but have question regarding mockup. How block should looks like when multiple authors are added?
Screen Shot 2023-03-01 at 3 35 25 PM

The configuration part looks like

**Comment by VladimirZaets** [comment]
Updated to support 
Screen Shot 2023-03-02 at 7 47 31 PM
updated index data on main blog page

**Comment by amol-anand** [comment]
@VladimirZaets Logic is looking good. couple of things in the CSS.

Screenshot 2023-03-06 at 11 16 05 AM

- There should be a space after "By" before the author info comes in.
- Multiple authors should wrap to the next line when the width is smaller and the content doesn't fit well in one line.

**Comment by VladimirZaets** [comment]
@amol-anand updated styles. Thanks

**Review by amol-anand — APPROVED** [review]

**Pull request merged**
