### PR TITLE
Navattic page blocks.

### PR DESCRIPTION
**Pull request by nimithshetty17**
## Issue

Fixes #[MERATIVE-871](https://merative.atlassian.net/browse/MERATIVE-871)

## Description

This is a request made to improve/optimize the user experience of the Navattic demo
The demo page template currently lives within AEM, however, it needs to be moved into Franklin as part of the phase 3 migration effort.

- Figma Link - https://www.figma.com/file/9THM4wHxEECVNzFpjuZZre/Navattic-Demo?type=design&node-id=767-8217&mode=design&t=DoD9UkeRkgughMDP-0

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/drafts/nimith/navattic-page
- After (Changes from this PR): https://navattic-page-blocks--merative2--nimithshetty17.hlx.page/drafts/nimith/navattic-updated

### CODE REVIEW

**Comment by keith-kaplan** [comment]
@nimithshetty17  let's make the footer for the demos a Fragment since that shouldn't be changed by an author.

**Review by sachinmesh — CHANGES_REQUESTED** [review]
1. Horizontal product logo text is missing. 
image

2. The divider line color should be Neutral 140 i.e. 5C5A57
image

3. Hamburger menu is missing on mobile.
    
image


4. Footer font style on mobile should be 14px light
    
image

@nimithshetty17 @keith-kaplan @anabarcelona

**Comment by nimithshetty17** [comment]
@keith-kaplan have created and added two fragments for header and footer from the approach Charity had suggested and they can be viewed here:- https://navattic-page-blocks--merative2--nimithshetty17.hlx.page/drafts/nimith/navattic-updated.
Let me know if this is the expected approach.

**Comment by nimithshetty17** [comment]
@sachinmesh the below issues are addressed:-

1. Horizontal product logo text is missing. - Fixed
2. The divider line color should be Neutral 140 i.e. 5C5A57 - Fixed
3. Hamburger menu is missing on mobile. - Fixed
4. Footer font style on mobile should be 14px light - Fixed 

Please have a look and let me know if there are more.

**Comment by nimithshetty17** [comment]
> @nimithshetty17 I created another demo for Micromedex and just saw that the CTA styling is broken when only using on button. Can we make sure the formatting is still correct even if one CTA is present?
> 
> https://navattic-page-blocks--merative2--nimithshetty17.hlx.page/clinical-decision-support/demo

@keith-kaplan for solution it has to be authored by adding a field called CTA and the buttons below. Please check https://navattic-page-blocks--merative2--nimithshetty17.hlx.page/clinical-decision-support/demo.

**Comment by sachinmesh** [comment]
1. On mobile and tablet, product logo should be 36px height. 
image


2. There should not be any vertical separator line after the logo.

@nimithshetty17 @keith-kaplan @anabarcelona

**Comment by nimithshetty17** [comment]
1. On mobile and tablet, product logo should be 36px height. - fixed
2. There should not be any vertical separator line after the logo. - fixed
@sachinmesh

**Comment by sachinmesh** [comment]
Looking good to me. Thank you @nimithshetty17 

@keith-kaplan @anabarcelona

**Review by sachinmesh — APPROVED** [review]

**Review by sachinmesh — CHANGES_REQUESTED** [review]
1. Need to remove the white divider line at the bottom of the iframe. 
image


2. Add links to the footer tabs and on hover add white underline.

@nimithshetty17 @keith-kaplan @anabarcelona

**Comment by nimithshetty17** [comment]
@sachinmesh - Removed the white line below iframe.
@keith-kaplan we are good to merge the PR.

**Review by sachinmesh — APPROVED** [review]

**Comment by sachinmesh** [comment]
The footer links should not be in purple, on hover a white underline will come.
image

@nimithshetty17 @keith-kaplan @anabarcelona

**Comment by nimithshetty17** [comment]
@sachinmesh - Footer issues have been addressed.
@keith-kaplan @anabarcelona

**Pull request merged**
