### PR TITLE
chore(csp): Update CSP to allow *.hotjar.io wss://*.hotjar.com

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - 

## Description

**Changed**

- This PR updates both CSPs on Franklin to allow for `*.hotjar.io` and `wss://*.hotjar.com`
- This will hopefully address the connection blocking issue that we're seeing on Live/prod.
Screen Shot 2023-06-16 at 12 39 03 PM

## Design Specs

- Figma Link - N/A

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/
- After (Changes from this PR): https://chore-csp-for-ws-hotjar--merative2--proeung.hlx.page
  
## Testing Instruction

- No testing instruction is needed.

### CODE REVIEW

**Review by keith-kaplan — CHANGES_REQUESTED** [review]
Looking at the guidance from Hotjar I think we only need to have *.hotjar.io wss://*.hotjar.com on the connect-src versus all the other properties. Can we try updating that so it make this a bit smaller?

https://help.hotjar.com/hc/en-us/articles/115011640307-Content-Security-Policies

**Comment by proeung** [comment]
@keith-kaplan Thanks for pointing that out. Please see the new commit here - https://github.com/hlxsites/merative2/pull/240/commits/7369543e4edcafa5db2e56c7a15b88aad430fc27

**Comment by keith-kaplan** [comment]
looks good. I think the lighthouse check failed.

**Comment by proeung** [comment]
@keith-kaplan Just re-run the psi-check CI.

**Comment by proeung** [comment]
@amol-anand @helms-charity Perhaps this is a known issue, but I keep getting inconsistent page performance scores from the `helix-psi-check`, despite not pushing any new code. Do you know why that is?

**Review by keith-kaplan — APPROVED** [review]
looks good

**Pull request merged**
