### PR TITLE
chore(csp): add Adobe Target Script and Salesloft Script

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://github.com/hlxsites/merative2/issues/289

## Description

**Changed**

- This PR updates both CSPs on Franklin to allow for `*.tt.omtrdc.net` and `*.salesloft.com`
- See screenshots for the current issues.

image

image

## Design Specs

- Figma Link - N/A

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/
- After (Changes from this PR): https://289-chore-update-csp--merative2--proeung.hlx.page
  
## Testing Instruction

- No testing instruction is needed.

### CODE REVIEW

**Review by keith-kaplan — CHANGES_REQUESTED** [review]
This is looking good. Salesloft is fixed, but it looks like Target also need to be add into another area. Can you add "*.tt.omtrdc.net" to styl-src as well

image

**Comment by proeung** [comment]
@keith-kaplan Done. Please check the latest commit.

**Review by keith-kaplan — APPROVED** [review]

**Comment by keith-kaplan** [comment]
@proeung  this looked like it fixed the issue. I'm going to submit an Adobe Support ticket to just ensure we have all things setup in Target properly. There are a few other errors I'm seeing in the console when editing and want to make sure I'm not missing anything.

**Comment by proeung** [comment]
@keith-kaplan Sounds good! Also, feel free to capture those errors that you see in the console in a ticket so that we can help debug where the issue is coming from. In the meantime, I'll go ahead and merge this PR down.

**Pull request merged**
