### PR TITLE
fix(blog-landing):fix design QA bugs to ensure the page aligns with the Design specs

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes https://github.com/hlxsites/merative2/issues/264

## Description

**Changed**

- This PR addresses all of the design issues seen on production and ensures that this landing page aligns with the design specs for all breakpoints.
- Add fluent container 
- **Context:** The Merative.com Blog (https://www.merative.com/blog) has been launched for a while now, however, during the development phase of this project, there we no proper design QA review implemented, which resulted in container alignment and spacing issues.

## Design Specs

- Figma Link - https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=202%3A67025&mode=dev 

## Test URLs

- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/blog
- After (Changes from this PR): https://fix-blog-landing-design-qa--merative2--proeung.hlx.page/blog
  
## Testing Instruction

- Visit this example page - https://fix-blog-landing-design-qa--merative2--proeung.hlx.page/blog
- Ensure that the changes align with the design specs for all of the support breakpoints

### CODE REVIEW

**Comment by anabarcelona** [comment]
Hi @proeung, will let @sachinmesh do a more detailed design QA but from my review it's looking good! Just a couple of things below:

Desktop: dev on left / design on right

A.
image
1. The main content well starting with the Merative Blog title needs to shift down. It needs 96px at the top. 

B.
image
1. We need two cards at the bottom. Noticing when you hit load more there's always a missing card on the right...
2. Load more button- please un-bold the number.

**Comment by anabarcelona** [comment]
@proeung @sachinmesh 

Desktop: Dev on left / design on right

C.
image
1. Left filters- Checkmark looks too bold compared to the design

**Comment by anabarcelona** [comment]
@proeung @sachinmesh 

Below is some feedback for mobile- will let Sachin take a more in-depth review, but looking good!

Mobile- Dev on left / Design on right

A.
image
1. The feature card photo is a bit taller than the other secondary blog cards. Please adjust. Feature card image height on mobile: 328x287px, secondary card image height on mobile: 328x219px (we have a 3x2 image ratio for our secondary cards)
2. The type size for Filters is too large. 
3. When you select some filters, we need a way to clear them on mobile. @sachinmesh, did you want to explore some options?
4. When you deselect the filters on mobile the empty state is showing as Filters (0). Let's remove the (0).

**Comment by sachinmesh** [comment]
Hi @proeung with @anabarcelona comments above, i am adding my observations here.
1. The spacing between sidebar and right content should be 48px. Its 46px now.
image


2. This spacing inside the card should be 24px and not 32px.
image

**Comment by proeung** [comment]
@helms-charity or @sahmad-merative Can I get a code review for this PR? Thanks!

**Review by helms-charity — APPROVED** [review]

**Comment by proeung** [comment]
I'm going to go ahead and merge the changes in this PR since the majority of the Design QA issues have been addressed. Also, we need to update these changes into the `feat/thought-leadership` branch so that we don't have any conflict/overlapping.

@sachinmesh If you notice any other display issues within this deploy preview (https://fix-blog-landing-design-qa--merative2--proeung.hlx.page/blog), please open a JIRA ticket and I'll address them with a new PR.

**Pull request merged**
