### PR TITLE
Issue 914

### PR DESCRIPTION
**Pull request by Ajeet-Nellikeri**
## Issue

Fix : https://merative.atlassian.net/browse/MERATIVE-914

## Test URLs
  
- Before: 

1. https://main--merative2--hlxsites.hlx.page/support/curam
2. https://main--merative2--hlxsites.hlx.page/support/micromedex

- After:

1. https://Issue-914--merative2--hlxsites.hlx.page/support/curam
2. https://Issue-914--merative2--hlxsites.hlx.page/support/micromedex

  
## Description

**Issue link:** https://merative-my.sharepoint.com/:w:/r/personal/abarcelona_merative_com/_layouts/15/Doc.aspx?sourcedoc=%7B75611843-70d7-4e83-b416-b66141541e34%7D&action=view&wdAccPdf=0&wdparaid=633D6286

Curam product support: Issue C.
Micromedex product support: Issue C.

## Note:
The  changes are generic and affects all the support pages where  "content-text-body" and "short-cards" blocks are used.

### CODE REVIEW

**Comment by sachinmesh** [comment]
@Ajeet-Nellikeri 

Only the spacing between the bullet points should be 8px.
image

CC: @keith-kaplan

**Review by sachinmesh — CHANGES_REQUESTED** [review]
image
Spacing between the bullet points to be 8px.

**Comment by Ajeet-Nellikeri** [comment]
@sachinmesh - Spacing between the bullet points to be 8px in Micromedex fixed

**Review by sachinmesh — APPROVED** [review]
Spacing between the bullet text is 8px now as per design. This is good to go @Ajeet-Nellikeri @keith-kaplan

**Review by keith-kaplan — APPROVED** [review]
Looks good.

**Pull request merged**
