### PR TITLE
feat(support-landing): add Short Cards and Content Text Body blocks

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes https://jira.sdlc.merative.com/browse/MERATIVE-893 and https://jira.sdlc.merative.com/browse/MERATIVE-894

## Description
- This PR adds blocks and styles needed for the new design of the Support Hub Landing as well as Product/Brand Support Landing. 

**New**

- `Short Cards` block - used for creating CTA cards for showing brand/product logos or support with graphic links.
- `Content Text Body` block - 2/3 body that displays texts, links, lists, etc.

## Design Specs

- Figma Link - https://www.figma.com/file/PgG604uUME84O2wSdLcln2/Support-Experience?type=design&node-id=457%3A19481&mode=design&t=M3Aau9H1Kft66ENo-1

### Support Hub Landing
Screenshot 2023-09-20 at 2 52 29 PM

- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/support
- After (Changes from this PR): https://feat-card-cta-893--merative2--proeung.hlx.page/support

### Product Support Landing
Screenshot 2023-09-20 at 2 51 54 PM

- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/support/curam
- After (Changes from this PR): https://feat-card-cta-893--merative2--proeung.hlx.page/support/curam

### Product Support Landing
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/support/micromedex
- After (Changes from this PR): https://feat-card-cta-893--merative2--proeung.hlx.page/support/micromedex

## Testing Instruction

- Visit the preview links above and ensure that the front-end display matches with the design.

### CODE REVIEW

**Review by sachinmesh — CHANGES_REQUESTED** [review]
1. On desktop, vertical padding between cards should be 48px

image


2. On product support, Caret issue in tab and mobile.

image



3. Issue when resizing from mobile to tab to desktop. Could be cache memory issue.
image

4. Alignment issue of cards in Tab/mobile. They should be inline with the heading. 

image

5. Padding issues on right side on tablet and mobile in below the cards

**Review by sharathmrft — CHANGES_REQUESTED** [review]
@proeung 
1.'Other products' icon is deferent than the design

2.Short cards all are not displaying in one shot in tab view these are horizontally placed
oth
shortcards
@sachinmesh

**Review by sachinmesh — APPROVED** [review]
All is good to go @proeung @sharathmrft 
Only seeing icon is not changed, hopefully it will reflect in production.
image

**Review by sharathmrft — APPROVED** [review]
@proeung 
Looking good to me

@sachinmesh

**Pull request merged**
