### PR TITLE
fix(article-body): Adjust article body to align with design specs

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes https://github.com/hlxsites/merative2/issues/195
  
## Description
- This PR adds style changes to the blog/article body to match the design specs.
- `Pullquote` block now displays the styles from the design
- `Featured Solution` block has been added to style the listing - https://fix-195-article-body-style--merative2--proeung.hlx.page/block-library/blocks/featured-solution

## Design Specs
- Figma - https://www.figma.com/file/dFJwrp6VkUMSirF2KMLRMx/Thought-leadership-library?type=design&node-id=357%3A17984&t=iaNohDrbt4220FLs-1

## Test URLs
  
- Before: https://main--merative2--hlxsites.hlx.page/drafts/putra/test-blog-detail-page
- After: https://fix-195-article-body-style--merative2--proeung.hlx.page/drafts/putra/test-blog-detail-page

## Testing Instruction

- Visit this test blog page - https://fix-195-article-body-style--merative2--proeung.hlx.page/drafts/putra/test-blog-detail-page
- Scroll down and ensure that the `Pull-quote` block matches the design
- Scroll down and ensure that the `Featured Solution` block matches the design
- Ensure that the Video embed includes a title

## Notes

- We'll need to update the content entry enablement to ensure that Content Authors understand the different blocks and text formats they should be using in the [SharePoint doc](https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B471AE649-EB64-4BDD-9961-E1CC011F020A%7D&file=test-blog-detail-page.docx&action=default&mobileredirect=true). @keith-kaplan Can you let me know if we have a process for updating Authors on changes?
- This PR is based on the `main` branch instead of `feat/thought-leadership` because these styles are part of the Blog and can be released before the Thought Leadership work has been completed.

### CODE REVIEW

**Comment by sachinmesh** [comment]
Hi,

1. The spacing above and below the quote should be 96px.

image

2. The spacing above and below the video player component should be 64px.

3. The font style for highlighted table of content should be H5 i.e. Alliance no.1 16px Regular and not semibold.
    it is showing semibold now 
image

4. The spacing below the table of contents to the divider line should be only 48px.


CC: @proeung @helms-charity

**Comment by proeung** [comment]
@sachinmesh I pushed up a commit that addresses your feedback. Can you take a look again?

**Review by helms-charity — APPROVED** [review]
Although I think you could accomplish the` featured-solution` block requirements via a `columns (featured-solution)` block, I will leave it up to you if you think it will be easier for Authors. As you know, less is more ;-)

**Comment by proeung** [comment]
@helms-charity Thanks for the review! This `Featured Solution` is a compound component within our design system and will be used in other places outside of the article body, therefore, it's important that we have it available in the Library listing so that it's easy for Content Authors to copy and paste in their doc.

> Also, whenever new blocks are created, they should be added to the Sidekick block library. You can create another ticket for that when you are ready.

I went ahead and added this new block to the list/spreadsheet and we'll note the availability/usage of this within the context of the Article content entry process for the Content Authors. FYI. @keith-kaplan 

Screen Shot 2023-06-12 at 3 41 50 PM

**Comment by sachinmesh** [comment]
Checked and its good to go.

@proeung @helms-charity

**Pull request merged**
