### PR TITLE
fix(state-campaign): address design QA issues seen on the Curam's Missouri state page

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://jira.sdlc.merative.com/browse/MERATIVE-880

## Description

**Changed**

- This PR fixes issues that came out of the design QA of the Curam's Missouri state page/campaign
- **Note:** The video lightbox/model feature will be addressed in a different ticket (https://jira.sdlc.merative.com/browse/MERATIVE-858). In the meantime, any of the CTAs that are linking out to YT, etc will be opened in a new tab.

## Design Specs

- Figma Link - https://www.figma.com/file/lcNLadWizxvzfhBpqds4hU/Curam---State-Microsite?type=design&node-id=664%3A1613&mode=design&t=BbUoqrz9MjDWQH1J-1

## Test URLs

Screenshot 2023-09-08 at 1 13 33 PM
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/campaigns/curam/missouri
- After (Changes from this PR): https://fix-design-qa-880--merative2--proeung.hlx.page/campaigns/curam/missouri
  
## Testing Instruction

- Visit this deploy preview page (https://fix-design-qa-880--merative2--proeung.hlx.page/campaigns/curam/missouri)
- Ensure that each band/pattern is displaying correctly for all breakpoints.

### CODE REVIEW

**Comment by proeung** [comment]
@aavilamer @anabarcelona Can you take a look at the preview (see PR description) and let me know if there are issues that need to be addressed?

Also, I changed the "Helpful Resources" to use the Linkable Cards/Card List pattern since it can handle linking to pages that don't have feature images (see attached).

Screenshot 2023-09-08 at 1 48 00 PM

**Review by sharathmrft — COMMENTED** [review]
@proeung Testimonial at the bottom is breaking as below
image

**Comment by anabarcelona** [comment]
Hi @proeung, It's looking good! Below are some minor tweeks:

1. 
image
Update the color of the background quarter circle to our Orange 60

2. Will take some screenshots of the videos and share them. Should I share them in this ticket?

3. Need link to CCWIS standards

4. Need hire rez screenshot for the product tour.

5. Let's remove the 3rd repeated case study in the rotator for now.

6. Update the color of Helpful resources section to bone

7. About Curam section looks like the image height needst o be adjusted. If text is too long causing the gap, let's have the copy reduced.

Exciting!!

**Comment by proeung** [comment]
@sharathmrft @anabarcelona Thanks for testing this PR. Please see my response to your findings below.

> Testimonial at the bottom is breaking as below

Fixed

> 2.Inline link should be highlighted.

Fixed

> 3,Address is missing at the bottom

This is content entry related. We don't need the address in this section.

> Update the color of the background quarter circle to our Orange 60

@anabarcelona This is content entry related. These images can be exported and added to Franklin's sharepoint doc when the assets are ready.

> Will take some screenshots of the videos and share them. Should I share them in this ticket?

@anabarcelona Please update them in the Figma project and I can export them when it's ready.

> Need link to CCWIS standards

Content entry related. Links can be updated in the Sharepoint doc.

> Let's remove the 3rd repeated case study in the rotator for now.

Done. Content updated in the Sharepoint doc.

> Update the color of Helpful resources section to bone

Done. Content updated in the Sharepoint doc.

> About Curam section looks like the image height needst o be adjusted. If text is too long causing the gap, let's have the copy reduced.

The copy of this section can be adjusted in the Sharepoint doc.

**Comment by anabarcelona** [comment]
Hi @proeung, I've updated the design with semi final imagery. We are still waiting on Liz to confirm imagery we've used as well as confirm the final links to the videos.

Please find the latest design updates here:
https://www.figma.com/file/lcNLadWizxvzfhBpqds4hU/Curam---State-Microsite?type=design&node-id=664%3A1613&mode=design&t=6h5j4udGRWLhnzCQ-1

**Comment by proeung** [comment]
@anabarcelona Thanks for the update! I'll export these assets and add them to Franklin, once we get final confirmation from Liz.

**Review by keith-kaplan — APPROVED** [review]
This is looking good!

**Pull request merged**
