### PR TITLE
feat(merative-history): add static build artifacts

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes https://jira.wh-sdlc.watson-health.ibm.com/browse/MERATIVE-726

## Description

**Changed**

- This PR adds the static build artifacts (html/css/js) of the Merative's History page (https://www.ibm.com/resources/watson-health/merative-history/) that's currently hosted on ibm.com.
- New directory `/resources/history/`
- We need a way to host these files because IBM will most likely sunset this URL on **June 30, 2023**. 

**Note**
- We need to figure out a way to set `index.html` as the home of `/resources/history/`

## Design Specs

- Figma Link - N/A

## Test URLs
  
Screen Shot 2023-06-22 at 4 33 49 PM

- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.live/
- After (Changes from this PR): https://feat-add-merative-history--merative2--proeung.hlx.page/resources/history/index.html
  
## Testing Instruction

- Open the IBM-hosted version of Merative's history - https://www.ibm.com/resources/watson-health/merative-history/
- Compare it with the version in this repo - https://feat-add-merative-history--merative2--proeung.hlx.page/resources/history/index.html
- Ensure that the design and interaction is the same.

### CODE REVIEW

**Comment by proeung** [comment]
@keith-kaplan @nimithshetty17 I decided to host these static build artifacts in the `/resources/history` of this repo and it seems to work. Can you take a look at the DOM elements of the `index.html` and let me know if there are other tags that are missing? I added the Adobe Tag Manager, but I'm sure there is other metadata that's needed.

**Comment by proeung** [comment]
**Note:** Also, LHS might be low because these images are in `.png`. I can convert them into `.webp`, if we feel good about what's in this PR.

**Review by keith-kaplan — CHANGES_REQUESTED** [review]
We need to add in the One Trust Script that is being used. It's hard coded on our AEM pages. Here's the code:
It should be added before the Launch script
`

<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js" type="text/javascript" charset="UTF-8" data-domain-script="8ec6325b-122f-4c25-93ea-b311a7f0ef97"></script>
--
  | <script type="text/javascript">
  | function OptanonWrapper() { }
  | </script>

`

**Comment by helms-charity** [comment]
I see a problem with putting this under /resources, because that is going to AEMaaCS I believe. You should put it in a different folder.

**Comment by proeung** [comment]
@keith-kaplan The One Trust script has been added (see - https://github.com/hlxsites/merative2/pull/251/commits/6f7ca7f1f1aa3f1770f421a623279256c9507984).

> I see a problem with putting this under /resources, because that is going to AEMaaCS I believe. You should put it in a different folder.

@helms-charity That shouldn't be an issue as we're going to remove the `/resource` from AEMaaCS. 

@nimithshetty17  Can you remove any references of `/resources` or `/resources/history` on our AEM's environments?

**Comment by proeung** [comment]
Marking this PR as "On-Hold" until we know which copy to use for the rebranding SPM to Cúram (see - https://merative.monday.com/boards/3096780490/views/92911261).

**Comment by proeung** [comment]
Added copy changes based on the changes outlined in this Monday.com card (https://merative.monday.com/boards/3096780490/views/92911261/pulses/4537485904/posts/2239610770).

@venky-moonraft @keith-kaplan Can you take a look?

Screen Shot 2023-06-26 at 2 31 34 PM

https://feat-add-merative-history--merative2--proeung.hlx.page/resources/history/index.html

**Comment by keith-kaplan** [comment]
@proeung  may we please move the Tag manager script below the Onetrust script? The Onetrust script needs to load first so if visitors choose to not accept cookies, some of the tag manager scripts won't load.

image

**Comment by proeung** [comment]
> @proeung may we please move the Tag Manager script below the Onetrust script? The Onetrust script needs to load first so if visitors choose to not accept cookies, some of the tag manager scripts won't load.

@keith-kaplan That's good to know. I was just following the script load order that we had on the AEM dev environment (view-source:https://dev.merative.com/resources/history).

Changes are up, can you take a look again? https://github.com/hlxsites/merative2/pull/251/commits/5bfebccb860e15869f2346e3490409239af85c00

**Comment by keith-kaplan** [comment]
Looks great. Thank you.

**Review by keith-kaplan — APPROVED** [review]

**Comment by venky-moonraft** [comment]
Looks good @proeung

**Review by nimithshetty17 — APPROVED** [review]

**Pull request merged**
