### PR TITLE
feat(headshot-list-marketo): add Headshot Link block as fragment below body text area - 774 & 859

### PR DESCRIPTION
**Pull request by proeung**
## Issue

Fixes - https://jira.sdlc.merative.com/browse/MERATIVE-774 and https://jira.sdlc.merative.com/browse/MERATIVE-859

## Description

**New**

- This PR adds a new block called `headshot-list` that acts as a content fragment, querying the `people/query-index.json` and pulling in the metadata needed to display the author's information in the headshot list pattern.

**Changed**

- Clean up and alters the construction of the DOM to account for two columns.

## Content Author Changes
- Authors and contributors for some of the Events/Webinar will need to be moved into the `/people` directory within our SharePoint folder.
- We'll need to adjust the SharePoint doc structure to account for the metadata section for Webinar pages where the Marketo form is located on the left-hand side and other contacts pages where it's displayed on the right column.
- @keith-kaplan @scottbridgeman We'll need to update the existing pages where Marketo is being used so that they're using the proper metadata classes (see below).
- **Regular content body with two columns (Left Col: Text/Body) | (Left Col: Marketo Form)**
  - [SharePoint Draft example](https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B2990610C-2FFD-44F8-B641-1606E7E05D51%7D&file=leverage-real-world-data-in-the-cloud.docx&action=default&mobileredirect=true)
  - Preview: https://feat-headshot-list-774--merative2--proeung.hlx.page/drafts/putra/leverage-real-world-data-in-the-cloud
  - Screenshot 2023-08-15 at 5 02 09 PM

- **Regular content body with two columns (Left Col: Marketo Form) | (Left Col: Text/Body)**
  - [SharePoint example](https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B4DC293D3-BBAF-487F-854A-B57890928537%7D&file=contact.docx&action=default&mobileredirect=true)
  - https://feat-headshot-list-774--merative2--proeung.hlx.page/drafts/putra/contact
  - Screenshot 2023-08-15 at 5 01 36 PM

## Design Specs

- Figma Link - https://www.figma.com/file/FSqQ1LYrVSssEFOZuOnMIE/Final-page-layouts-for-Merative.com?type=design&node-id=1933-47557&mode=design&t=DKh0qauOISJX3DEG-4

## Test URLs
  
- Before (Changes from `main`): https://main--merative2--hlxsites.hlx.page/drafts/putra/leverage-real-world-data-in-the-cloud
- After (Changes from this PR): https://feat-headshot-list-774--merative2--proeung.hlx.page/drafts/putra/leverage-real-world-data-in-the-cloud
  
## Testing Instruction

Screenshot 2023-08-15 at 5 04 06 PM

- Visit the new draft page that includes the test content where the author's info is pulled from the `/people` directory. https://feat-headshot-list-774--merative2--proeung.hlx.page/drafts/putra/leverage-real-world-data-in-the-cloud
- Ensure that the page aligns with the design

### CODE REVIEW

**Review by scottbridgeman — APPROVED** [review]
@proeung  - changes look great! Thank you

**Comment by sachinmesh** [comment]
> * https://feat-headshot-list-774--merative2--proeung.hlx.page/drafts/putra/leverage-real-world-data-in-the-cloud

**1. Sorry, typo error here for 26px, it should be 16px.**

image


**2. On Mobile, the eyebrow font style should be 11px Alliance no.1 medium**

image


Rest is good to go.

@proeung @sharathmrft

**Comment by proeung** [comment]
@sachinmesh I just pushed up a commit that should address your latest comment. Can you take a look again?

**Review by sachinmesh — APPROVED** [review]
Good to go @proeung

**Review by keith-kaplan — CHANGES_REQUESTED** [review]
I did a test on the ism-2023 page and it looks like the H2 title of Registration is being added to the sidebar column. I think we need to add a row in the marketo form block that allows for the title to show above the form - https://feat-headshot-list-774--merative2--proeung.hlx.page/events/ism-2023

**Comment by proeung** [comment]
@keith-kaplan Thanks for testing this PR! I just pushed up fixes for the form title issue you mentioned. Please see links below for the content entry changes.

- Test Preview: https://feat-headshot-list-774--merative2--proeung.hlx.page/drafts/putra/ism-2023
- [Test Sharepoint Doc](https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B5BE81322-6DA3-4DB9-BDE0-91752C2FC3EF%7D&file=ism-2023.docx&action=default&mobileredirect=true)

Screenshot 2023-08-18 at 3 07 58 PM
Screenshot 2023-08-18 at 3 10 24 PM

**Comment by sharathmrft** [comment]
@proeung 
I have retested fixed issues commented by me those are fine.
@keith-kaplan @sachinmesh

**Comment by proeung** [comment]
@keith-kaplan I just pushed up some commits for the changes that we discussed on the call this morning. Also, I add a fix to the radio input display issue on mobile devices. I tested this on my iOS and it looks good (see attached), but would be good to have you test it as well. Let me know if you see anything odd.

Preview: https://feat-headshot-list-774--merative2--proeung.hlx.page/drafts/putra/ism-2023

**Comment by keith-kaplan** [comment]
Great. I'll start updating the other pages with this styling.

**Comment by keith-kaplan** [comment]
@proeung  can you take a look at the styling here for the bulleted list? https://feat-headshot-list-774--merative2--proeung.hlx.page/offers/real-world-evidence-trends

It looks like it's not the same font size as the paragraphs

image

**Review by keith-kaplan — APPROVED** [review]
Went through the /offers and /event pages and updated doc structure to accommodate these changes.

**Pull request merged**
